//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class note
    {
        public int notes_id { get; set; }
        public string file_name { get; set; }
        public string course_name { get; set; }
        public byte[] pdf_file { get; set; }
        public int user_id { get; set; }
        public int status { get; set; }
    
        public virtual user_info user_info { get; set; }
        [NotMapped]
        public string user_name
        {
            get { return user_info != null ? user_info.user_name : ""; }
        }
        public byte[] profile_pic
        {
            get { return user_info != null ? user_info.profile_pic : null; }
        }
    }
}
